version: "3"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "9001:8081"
    volumes:
      - nexus-data:/nexus-data
      - nexus-logs:/var/log/nexus
      - nexus-blobs:/nexus-data/blobs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure

volumes:
  nexus-data:
    external: true
  nexus-logs:
    external: true
  nexus-blobs:
    external: true
