version: '3.8'
services:

  user-microservice:
    build:
      context: ./backend
      dockerfile: user/Dockerfile
    ports:
      - "8443:8443"
    networks:
      - buy01-network
    depends_on:
      - kafka

  product-microservice:
    build:
      context: ./backend
      dockerfile: product/Dockerfile
    ports:
      - "8444:8444"
    networks:
      - buy01-network
    depends_on:
      - kafka

  media-microservice:
    build:
      context: ./backend
      dockerfile: media/Dockerfile
    ports:
      - "8445:8445"
    networks:
      - buy01-network
    depends_on:
      - kafka

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - buy01-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    networks:
      - buy01-network
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: '10000000'
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - buy01-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

networks:
  buy01-network:
    driver: bridge
