version: '3.8'
services:

  user-microservice:
    image: danglamgritlab/user-microservice:latest
    container_name: user-microservice-container
    ports:
      - "8443:8443"
    networks:
      - buy01-network
    depends_on:
      - kafka
      - user-mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  product-microservice:
    image: danglamgritlab/product-microservice:latest
    container_name: product-microservice-container
    ports:
      - "8444:8444"
    networks:
      - buy01-network
    depends_on:
      - kafka
      - product-mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8444/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  media-microservice:
    image: danglamgritlab/media-microservice:latest
    container_name: media-microservice-container
    ports:
      - "8445:8445"
    networks:
      - buy01-network
    depends_on:
      - kafka
      - media-mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8445/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: danglamgritlab/frontend:latest
    container_name: frontend-container
    ports:
      - "4200:4200"
    networks:
      - buy01-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-mongodb:
    image: mongo:latest
    container_name: user-mongodb-container
    ports:
      - "27018:27017"
    networks:
      - buy01-network
    volumes:
      - user-mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_DB_CREDENTIALS_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_DB_CREDENTIALS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  product-mongodb:
    image: mongo:latest
    container_name: product-mongodb-container
    ports:
      - "27019:27017"
    networks:
      - buy01-network
    volumes:
      - product-mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PRODUCT_DB_CREDENTIALS_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PRODUCT_DB_CREDENTIALS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  media-mongodb:
    image: mongo:latest
    container_name: media-mongodb-container
    ports:
      - "27020:27017"
    networks:
      - buy01-network
    volumes:
      - media-mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MEDIA_DB_CREDENTIALS_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MEDIA_DB_CREDENTIALS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-container
    ports:
      - "9092:9092"
    networks:
      - buy01-network
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: '10000000'
    depends_on:
      - zookeeper
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server=localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-container
    ports:
      - "2181:2181"
    networks:
      - buy01-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  user-mongo-volume:
    external: true
  product-mongo-volume:
    external: true
  media-mongo-volume:
    external: true

networks:
  buy01-network:
    driver: bridge
