version: '3.8'
services:

  user-microservice:
    image: danglamgritlab/user-microservice:latest
    ports:
      - "8443:8443"
    networks:
      - buy01-network
    depends_on:
      - kafka
      - user-mongodb

  product-microservice:
    image: danglamgritlab/product-microservice:latest
    ports:
      - "8444:8444"
    networks:
      - buy01-network
    depends_on:
      - kafka
      - product-mongodb

  media-microservice:
    image: danglamgritlab/media-microservice:latest
    ports:
      - "8445:8445"
    networks:
      - buy01-network
    depends_on:
      - kafka
      - media-mongodb

  frontend:
    image: danglamgritlab/frontend:latest
    ports:
      - "4200:4200"
    networks:
      - buy01-network

  user-mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - buy01-network
    volumes:
      - user-mongo-volume:/data/db

  product-mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    networks:
      - buy01-network
    volumes:
      - product-mongo-volume:/data/db

  media-mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    networks:
      - buy01-network
    volumes:
      - media-mongo-volume:/data/db

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    networks:
      - buy01-network
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: '10000000'
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - buy01-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  user-mongo-volume:
    external: true
  product-mongo-volume:
    external: true
  media-mongo-volume:
    external: true

networks:
  buy01-network:
    driver: bridge
